# Generated by Django 5.2.5 on 2025-12-13 16:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, verbose_name='№ документа / накладної')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата і час')),
                ('weight_gross', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Вага брутто (тонн)')),
                ('weight_tare', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Вага тара (тонн)')),
                ('weight_loss', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вага втрат (тонн)')),
                ('weight_net', models.DecimalField(decimal_places=3, editable=False, max_digits=12, verbose_name='Вага нетто (тонн)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.car', verbose_name='Автомобіль')),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.culture', verbose_name='Культура')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.driver', verbose_name='Водій')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_outcomes', to='directory.field', verbose_name='Поле')),
                ('place_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_incomes', to='directory.place', verbose_name='Місце прийому')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.trailer', verbose_name='Причеп')),
            ],
            options={
                'verbose_name': 'Журнал надходжень з полів',
                'verbose_name_plural': 'Журнали надходжень з полів',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, verbose_name='№ документа / накладної')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата і час')),
                ('weight_gross', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Вага брутто (тонн)')),
                ('weight_tare', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Вага тара (тонн)')),
                ('weight_loss', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вага втрат (тонн)')),
                ('weight_net', models.DecimalField(decimal_places=3, editable=False, max_digits=12, verbose_name='Вага нетто (тонн)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('action_type', models.CharField(choices=[('import', 'Ввезення'), ('export', 'Вивезення')], max_length=10, null=True, verbose_name='Тип операції')),
                ('place_from_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Місце з (текст)')),
                ('place_to_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Місце до (текст)')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.car', verbose_name='Автомобіль')),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.culture', verbose_name='Культура')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.driver', verbose_name='Водій')),
                ('place_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='directory.place', verbose_name='Місце з')),
                ('place_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='directory.place', verbose_name='Місце до')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.trailer', verbose_name='Причеп')),
            ],
            options={
                'verbose_name': 'Журнал відвантажень',
                'verbose_name_plural': 'Журнали відвантажень',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='WeigherJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, verbose_name='№ документа / накладної')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата і час')),
                ('weight_gross', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Вага брутто (тонн)')),
                ('weight_tare', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Вага тара (тонн)')),
                ('weight_loss', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вага втрат (тонн)')),
                ('weight_net', models.DecimalField(decimal_places=3, editable=False, max_digits=12, verbose_name='Вага нетто (тонн)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.car', verbose_name='Автомобіль')),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.culture', verbose_name='Культура')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.driver', verbose_name='Водій')),
                ('from_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighings_from', to='directory.place', verbose_name='З місця')),
                ('to_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighings_to', to='directory.place', verbose_name='До місця')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.trailer', verbose_name='Причеп')),
            ],
            options={
                'verbose_name': 'Журнал внутрішніх переміщень',
                'verbose_name_plural': 'Журнали внутрішніх переміщень',
                'ordering': ['-date_time'],
            },
        ),
    ]
