# Generated by Django 5.2.5 on 2025-11-06 18:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0003_alter_car_options_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, verbose_name='№ документа / накладної')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата і час')),
                ('weight_gross', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Вага брутто (тонн)')),
                ('weight_tare', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Вага тара (тонн)')),
                ('weight_net', models.DecimalField(decimal_places=3, editable=False, max_digits=12, verbose_name='Вага нетто (тонн)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('place_from_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Місце з (текст)')),
                ('place_to_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Місце до (текст)')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.car', verbose_name='Автомобіль')),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.culture', verbose_name='Культура')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.driver', verbose_name='Водій')),
                ('place_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='directory.place', verbose_name='Місце з')),
                ('place_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='directory.place', verbose_name='Місце до')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.trailer', verbose_name='Причеп')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeigherJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, verbose_name='№ документа / накладної')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата і час')),
                ('weight_gross', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Вага брутто (тонн)')),
                ('weight_tare', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Вага тара (тонн)')),
                ('weight_net', models.DecimalField(decimal_places=3, editable=False, max_digits=12, verbose_name='Вага нетто (тонн)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.car', verbose_name='Автомобіль')),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.culture', verbose_name='Культура')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.driver', verbose_name='Водій')),
                ('from_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighings_from', to='directory.place', verbose_name='З місця')),
                ('to_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighings_to', to='directory.place', verbose_name='До місця')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.trailer', verbose_name='Причеп')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('type', models.CharField(choices=[('stock', 'Зерно'), ('waste', 'Відходи')], max_length=10)),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.culture')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.place')),
            ],
            options={
                'unique_together': {('place', 'culture', 'type')},
            },
        ),
    ]
