# Generated by Django 5.2.5 on 2025-08-24 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0003_partner_unloadingplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, verbose_name='№ документа / накладної')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата і час')),
                ('weight_gross', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вага брутто (кг)')),
                ('weight_tare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вага тари (кг)')),
                ('weight_net', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Вага нетто (кг)')),
                ('driver_signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='Підпис водія (електронний)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.car', verbose_name='Автомобіль')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.culture', verbose_name='Культура')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.driver', verbose_name='Водій')),
                ('receiver', models.ForeignKey(limit_choices_to={'partner_type__in': ['receiver', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='received_trips', to='directory.partner', verbose_name='Отримувач')),
                ('sender', models.ForeignKey(limit_choices_to={'partner_type__in': ['sender', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_trips', to='directory.partner', verbose_name='Відправник')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.trailer', verbose_name='Причеп')),
                ('unloading_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.unloadingplace', verbose_name='Місце розвантаження')),
            ],
        ),
    ]
