# Generated by Django 5.2.5 on 2026-06-11 08:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, verbose_name='№ документа / накладної')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата і час')),
                ('weight_gross', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Вага брутто (тонн)')),
                ('weight_tare', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Вага тара (тонн)')),
                ('weight_loss', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вага втрат (тонн)')),
                ('weight_net', models.DecimalField(decimal_places=3, editable=False, max_digits=12, verbose_name='Вага нетто (тонн)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('seller', models.CharField(max_length=255, verbose_name='Продавець')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.car', verbose_name='Автомобіль')),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.culture', verbose_name='Культура')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.driver', verbose_name='Водій')),
                ('place_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_incomes', to='directory.place', verbose_name='Місце прийому')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.trailer', verbose_name='Причеп')),
            ],
            options={
                'verbose_name': 'Журнал інших надходжень',
                'verbose_name_plural': 'Журнали інших надходжень',
                'ordering': ['-date_time'],
            },
        ),
    ]
