# Generated by Django 5.2.5 on 2025-08-25 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата і час'),
        ),
    ]
