# Generated by Django 5.2.5 on 2025-11-09 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_car_options_alter_driver_options_and_more'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentjournal',
            options={'ordering': ['-date_time'], 'verbose_name': 'Журнал відвантажень', 'verbose_name_plural': 'Журнали відвантажень'},
        ),
        migrations.AlterModelOptions(
            name='weigherjournal',
            options={'ordering': ['-date_time'], 'verbose_name': 'Журнал внутрішніх переміщень', 'verbose_name_plural': 'Журнали внутрішніх переміщень'},
        ),
        migrations.RemoveField(
            model_name='shipmentjournal',
            name='place_to_text',
        ),
        migrations.AlterField(
            model_name='shipmentjournal',
            name='place_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='directory.place', verbose_name='Місце до'),
        ),
    ]
