# Generated by Django 5.2.5 on 2025-09-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_trip_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver_signature',
        ),
    ]
