# Generated by Django 5.2.5 on 2026-06-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_otherincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='weigherjournal',
            name='to_balance_type',
            field=models.CharField(choices=[('stock', 'Зерно'), ('waste', 'Відходи')], default='stock', help_text='Визначає, як зараховується кількість на місці призначення: як зерно чи як відходи. На місці відправлення завжди списується зерно.', max_length=10, verbose_name='Приймається як'),
        ),
    ]
