# Generated by Django 5.2.5 on 2025-09-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_car_default_driver'),
        ('logistics', '0003_remove_trip_driver_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='WeigherJournal',
        ),
    ]
