# Generated by Django 5.2.5 on 2025-11-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_fieldsincome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldsincome',
            old_name='place_from',
            new_name='field',
        ),
    ]
