# Generated by Django 5.2.5 on 2025-11-13 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_car_options_alter_driver_options_and_more'),
        ('logistics', '0005_wastejournal_delete_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentjournal',
            name='action_type',
            field=models.CharField(choices=[('import', 'Ввезення'), ('export', 'Вивезення')], max_length=10, null=True, verbose_name='Тип операції'),
        ),
        migrations.AlterField(
            model_name='shipmentjournal',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='directory.place', verbose_name='Місце до'),
        ),
    ]
