# Generated by Django 5.2.5 on 2025-09-25 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_car_default_driver'),
        ('logistics', '0005_arrivaljournal_shipmentjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivaljournal',
            name='weight_gross',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Вага брутто (кг)'),
        ),
        migrations.AlterField(
            model_name='arrivaljournal',
            name='weight_net',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=100, verbose_name='Вага нетто (кг)'),
        ),
        migrations.AlterField(
            model_name='arrivaljournal',
            name='weight_tare',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Вага тари (кг)'),
        ),
        migrations.AlterField(
            model_name='shipmentjournal',
            name='weight_gross',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Вага брутто (кг)'),
        ),
        migrations.AlterField(
            model_name='shipmentjournal',
            name='weight_net',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=100, verbose_name='Вага нетто (кг)'),
        ),
        migrations.AlterField(
            model_name='shipmentjournal',
            name='weight_tare',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Вага тари (кг)'),
        ),
        migrations.AlterField(
            model_name='weigherjournal',
            name='weight_gross',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Вага брутто (кг)'),
        ),
        migrations.AlterField(
            model_name='weigherjournal',
            name='weight_net',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=100, verbose_name='Вага нетто (кг)'),
        ),
        migrations.AlterField(
            model_name='weigherjournal',
            name='weight_tare',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Вага тари (кг)'),
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Кількість (кг)')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='directory.culture', verbose_name='Культура')),
                ('unloading_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='directory.unloadingplace', verbose_name='Місце')),
            ],
            options={
                'unique_together': {('unloading_place', 'culture')},
            },
        ),
    ]
