# Generated by Django 5.2.5 on 2025-11-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_shipmentjournal_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentjournal',
            name='place_to_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місце з (текст)'),
        ),
    ]
