# Generated by Django 5.2.5 on 2025-09-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_arrivaljournal_weight_tare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivaljournal',
            name='weight_tare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Вага тари (кг)'),
        ),
    ]
