# Generated by Django 5.2.5 on 2025-11-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_shipmentjournal_place_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsincome',
            name='weight_loss',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Вага втрат (тонн)'),
        ),
        migrations.AddField(
            model_name='shipmentjournal',
            name='weight_loss',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Вага втрат (тонн)'),
        ),
        migrations.AddField(
            model_name='weigherjournal',
            name='weight_loss',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Вага втрат (тонн)'),
        ),
        migrations.AlterField(
            model_name='shipmentjournal',
            name='place_to_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місце до (текст)'),
        ),
    ]
