# Generated by Django 5.2.5 on 2025-11-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_fieldsincome_weight_loss_shipmentjournal_weight_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldsincome',
            name='weight_loss',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вага втрат (тонн)'),
        ),
        migrations.AlterField(
            model_name='shipmentjournal',
            name='weight_loss',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вага втрат (тонн)'),
        ),
        migrations.AlterField(
            model_name='weigherjournal',
            name='weight_loss',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вага втрат (тонн)'),
        ),
        migrations.DeleteModel(
            name='WasteJournal',
        ),
    ]
