# Generated by Django 5.2.5 on 2025-09-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_alter_arrivaljournal_weight_tare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weigherjournal',
            name='weight_tare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Вага тари (кг)'),
        ),
    ]
