# Generated by Django 5.2.5 on 2025-10-24 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_unloadingplace_cultures'),
        ('logistics', '0011_alter_weigherjournal_weight_tare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivaljournal',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.car', verbose_name='Автомобіль'),
        ),
        migrations.AlterField(
            model_name='arrivaljournal',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.culture', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='arrivaljournal',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.driver', verbose_name='Водій'),
        ),
        migrations.AlterField(
            model_name='arrivaljournal',
            name='sender_or_receiver',
            field=models.ForeignKey(limit_choices_to={'partner_type__in': ['sender', 'receiver', 'both']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.partner', verbose_name='Відправник / Отримувач'),
        ),
        migrations.AlterField(
            model_name='arrivaljournal',
            name='unloading_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.unloadingplace', verbose_name='Місце розвантаження'),
        ),
        migrations.AlterField(
            model_name='shipmentjournal',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.car', verbose_name='Автомобіль'),
        ),
        migrations.AlterField(
            model_name='shipmentjournal',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.culture', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='shipmentjournal',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.driver', verbose_name='Водій'),
        ),
        migrations.AlterField(
            model_name='shipmentjournal',
            name='sender',
            field=models.ForeignKey(limit_choices_to={'partner_type__in': ['sender', 'both']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_shipments', to='directory.partner', verbose_name='Відправник'),
        ),
        migrations.AlterField(
            model_name='shipmentjournal',
            name='unloading_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.unloadingplace', verbose_name='Місце розвантаження'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balances', to='directory.culture', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='unloading_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balances', to='directory.unloadingplace', verbose_name='Місце'),
        ),
        migrations.AlterField(
            model_name='weigherjournal',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.car', verbose_name='Автомобіль'),
        ),
        migrations.AlterField(
            model_name='weigherjournal',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.culture', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='weigherjournal',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.driver', verbose_name='Водій'),
        ),
        migrations.AlterField(
            model_name='weigherjournal',
            name='receiver',
            field=models.ForeignKey(limit_choices_to={'partner_type__in': ['receiver', 'both']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_trips', to='directory.partner', verbose_name='Отримувач'),
        ),
        migrations.AlterField(
            model_name='weigherjournal',
            name='sender',
            field=models.ForeignKey(limit_choices_to={'partner_type__in': ['sender', 'both']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_trips', to='directory.partner', verbose_name='Відправник'),
        ),
        migrations.AlterField(
            model_name='weigherjournal',
            name='unloading_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.unloadingplace', verbose_name='Місце розвантаження'),
        ),
    ]
