# Generated by Django 5.2.5 on 2025-11-16 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0003_alter_car_options_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час')),
                ('action', models.CharField(choices=[('utilization', 'Утилізація'), ('recycling', 'Переробка')], max_length=20, verbose_name='Дія')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість (т)')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.culture', verbose_name='Культура')),
                ('place_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_from', to='directory.place', verbose_name='Місце відправлення')),
                ('place_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_to', to='directory.place', verbose_name='Місце призначення (для переробки)')),
            ],
            options={
                'verbose_name': 'Журнал управління відходами',
                'verbose_name_plural': 'Журнали управління відходами',
                'ordering': ['-date_time'],
            },
        ),
    ]
