# Generated by Django 5.2.5 on 2025-11-17 18:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_car_options_alter_driver_options_and_more'),
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recycling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість (т)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('output_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість на виході (т)')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.culture', verbose_name='Культура')),
                ('place_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.place', verbose_name='Місце відправлення')),
                ('place_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycling_in', to='directory.place', verbose_name='Місце призначення')),
            ],
            options={
                'verbose_name': 'Переробка',
                'verbose_name_plural': 'Операції переробки',
            },
        ),
        migrations.CreateModel(
            name='Utilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість (т)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.culture', verbose_name='Культура')),
                ('place_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.place', verbose_name='Місце відправлення')),
            ],
            options={
                'verbose_name': 'Утилізація',
                'verbose_name_plural': 'Операції утилізації',
            },
        ),
        migrations.DeleteModel(
            name='WasteJournal',
        ),
    ]
