# Generated by Django 5.2.5 on 2025-12-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycling',
            name='input_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='output_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість на виході'),
        ),
        migrations.AlterField(
            model_name='utilization',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість'),
        ),
    ]
