# Generated by Django 5.2.5 on 2025-12-10 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва звіту')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('report_type', models.CharField(choices=[('balance', 'Залишки'), ('waste', 'Відходи'), ('weigher', 'Внутрішні переміщення'), ('shipment', 'Відвантаження'), ('fields', 'Надходження з полів'), ('income_date', 'Прихід зерна за дату'), ('balance_snapshot', 'Залишки за дату'), ('balance_period', 'Залишки за період'), ('income_period', 'Прихід зерна за період'), ('shipment_summary', 'Ввезення/вивезення за період'), ('custom', 'Власний звіт')], max_length=20, verbose_name='Тип звіту')),
                ('chart_type', models.CharField(choices=[('bar', 'Стовпчаста діаграма'), ('line', 'Лінійний графік'), ('pie', 'Кругова діаграма'), ('area', 'Площинний графік'), ('table', 'Тільки таблиця')], default='table', max_length=20, verbose_name='Тип візуалізації')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Формат виводу')),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON з налаштуваннями фільтрів, полів та формату', verbose_name='Конфігурація')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публічний')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Шаблон звіту',
                'verbose_name_plural': 'Шаблони звітів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час виконання')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата з')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата до')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Фільтри')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='Дані результату')),
                ('row_count', models.IntegerField(default=0, verbose_name='Кількість рядків')),
                ('report_type', models.CharField(max_length=20, verbose_name='Тип звіту')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Файл звіту')),
                ('file_format', models.CharField(default='pdf', max_length=10, verbose_name='Формат файлу')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Виконано')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.reporttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Виконання звіту',
                'verbose_name_plural': 'Історія виконань звітів',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('filters', models.JSONField(default=dict, verbose_name='Збережені фільтри')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('last_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportexecution', verbose_name='Останнє виконання')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='reports.reporttemplate', verbose_name='Шаблон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Збережений звіт',
                'verbose_name_plural': 'Збережені звіти',
                'ordering': ['-created_at'],
            },
        ),
    ]
