# Generated by Django 5.2.5 on 2025-12-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('balance', 'Залишки'), ('waste', 'Відходи'), ('weigher', 'Внутрішні переміщення'), ('shipment', 'Відвантаження'), ('fields', 'Надходження з полів'), ('income_date', 'Прихід зерна за дату'), ('balance_snapshot', 'Залишки за дату'), ('balance_period', 'Залишки за період'), ('income_period', 'Прихід зерна за період (старий)'), ('shipment_summary', 'Ввезення/вивезення за період'), ('total_income_period', 'Прихід зерна (Загальний за період)'), ('custom', 'Власний звіт')], max_length=20, verbose_name='Тип звіту'),
        ),
    ]
