# Generated by Django 5.2.5 on 2025-12-02 20:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0003_alter_car_options_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата зліпку')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Опис')),
                ('created_by', models.CharField(blank=True, default='система', max_length=100, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Зліпок залишків',
                'verbose_name_plural': 'Зліпки залишків',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_type', models.CharField(blank=True, choices=[('stock', 'Зерно'), ('waste', 'Відходи')], default='stock', max_length=10, null=True, verbose_name='Тип балансу')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, verbose_name='Кількість (тонн)')),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_history', to='directory.culture', verbose_name='Культура')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_history', to='directory.place', verbose_name='Місце зберігання')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='balances.balancesnapshot', verbose_name='Зліпок')),
            ],
            options={
                'verbose_name': 'Історія залишків',
                'verbose_name_plural': 'Історія залишків',
                'ordering': ['place', 'culture'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_type', models.CharField(choices=[('stock', 'Зерно'), ('waste', 'Відходи')], default='stock', max_length=10, verbose_name='Тип балансу')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Кількість (тонн)')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_records', to='directory.culture', verbose_name='Культура')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_records', to='directory.place', verbose_name='Місце зберігання')),
            ],
            options={
                'verbose_name': 'Залишок',
                'verbose_name_plural': 'Залишки',
                'ordering': ['place', 'culture', 'balance_type'],
                'unique_together': {('place', 'culture', 'balance_type')},
            },
        ),
    ]
