# Generated by Django 5.2.8 on 2025-12-01 18:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0003_alter_car_options_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Історія залишків',
                'verbose_name_plural': 'Історія залишків',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_type', models.CharField(choices=[('stock', 'Зерно'), ('waste', 'Відходи')], default='stock', max_length=10, verbose_name='Тип балансу')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Кількість (тонн)')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_records', to='directory.culture', verbose_name='Культура')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_records', to='directory.place', verbose_name='Місце зберігання')),
            ],
            options={
                'verbose_name': 'Залишок',
                'verbose_name_plural': 'Залишки',
                'ordering': ['place', 'culture', 'balance_type'],
                'unique_together': {('place', 'culture', 'balance_type')},
            },
        ),
    ]
