# Generated by Django 5.2.8 on 2025-12-01 19:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата зліпку')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Опис')),
                ('created_by', models.CharField(blank=True, default='система', max_length=100, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Зліпок залишків',
                'verbose_name_plural': 'Зліпки залишків',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='balancehistory',
            options={'ordering': ['place_name', 'culture_name'], 'verbose_name': 'Історія залишків', 'verbose_name_plural': 'Історія залишків'},
        ),
        migrations.RemoveField(
            model_name='balancehistory',
            name='snapshot_date',
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='balance_type',
            field=models.CharField(choices=[('stock', 'Зерно'), ('waste', 'Відходи')], default='stock', max_length=10, verbose_name='Тип балансу'),
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='culture_name',
            field=models.CharField(default='', max_length=255, verbose_name='Культура'),
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='place_name',
            field=models.CharField(default='', max_length=255, verbose_name='Місце зберігання'),
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Кількість (тонн)'),
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='balances.balancesnapshot', verbose_name='Зліпок'),
        ),
    ]
