# Generated by Django 5.2.5 on 2025-11-11 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
        ('directory', '0003_alter_car_options_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['place', 'culture', 'balance_type'], 'verbose_name': 'Залишок', 'verbose_name_plural': 'Залишки'},
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('place', 'culture', 'balance_type')},
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата зміни')),
                ('note', models.TextField(blank=True, verbose_name='Примітка')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='balances.balance', verbose_name='Залишок')),
            ],
            options={
                'verbose_name': 'Історія залишку',
                'verbose_name_plural': 'Історія залишків',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='balance',
            name='date',
        ),
    ]
