# Generated by Django 5.2.5 on 2025-11-13 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0002_alter_balance_options_alter_balance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancehistory',
            options={'ordering': ['-snapshot_date'], 'verbose_name': 'Історія залишків', 'verbose_name_plural': 'Історія залишків'},
        ),
        migrations.RemoveField(
            model_name='balancehistory',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='balancehistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='balancehistory',
            name='note',
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='snapshot_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
