# Generated by Django 5.2.5 on 2025-12-13 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ПІБ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Водій',
                'verbose_name_plural': 'Водії',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва поля')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва місця')),
                ('place_type', models.CharField(choices=[('storage', 'Склад'), ('canopy', 'Піднавіс'), ('factory', 'Завод'), ('dryer', 'Сушка'), ('other', 'Інше')], default='storage', max_length=50, verbose_name='Тип місця')),
            ],
            options={
                'verbose_name': 'Місце',
                'verbose_name_plural': 'Місця',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер причепа')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Коментар')),
            ],
            options={
                'verbose_name': 'Причеп',
                'verbose_name_plural': 'Причепи',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер авто')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва / Коментар')),
                ('default_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='directory.driver', verbose_name='Закріплений водій')),
            ],
            options={
                'verbose_name': 'Авто',
                'verbose_name_plural': 'Автомобілі',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва культури / підкультури')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcultures', to='directory.culture', verbose_name='Батьківська культура')),
            ],
            options={
                'verbose_name': 'Культура / Підкультура',
                'verbose_name_plural': 'Культури / Підкультури',
                'ordering': ['parent__name', 'name'],
                'unique_together': {('name', 'parent')},
            },
        ),
    ]
