# Generated by Django 5.2.5 on 2025-11-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва поля')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва місця')),
                ('place_type', models.CharField(choices=[('storage', 'Склад'), ('canopy', 'Піднавіс'), ('factory', 'Завод'), ('dryer', 'Сушка'), ('other', 'Інше')], default='storage', max_length=50, verbose_name='Тип місця')),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер причепа')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Коментар')),
            ],
        ),
        migrations.AlterModelOptions(
            name='culture',
            options={'ordering': ['parent__name', 'name'], 'verbose_name': 'Культура / Підкультура', 'verbose_name_plural': 'Культури / Підкультури'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='car',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='company',
        ),
        migrations.AddField(
            model_name='car',
            name='default_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='directory.driver', verbose_name='Закріплений водій'),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва / Коментар'),
        ),
        migrations.AddField(
            model_name='culture',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcultures', to='directory.culture', verbose_name='Батьківська культура'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва культури / підкультури'),
        ),
        migrations.AlterUniqueTogether(
            name='culture',
            unique_together={('name', 'parent')},
        ),
    ]
