# Generated by Django 5.2.5 on 2025-08-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер причепа')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Коментар')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='car',
            name='trailer',
        ),
        migrations.AddField(
            model_name='car',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Коментар'),
        ),
    ]
