# Generated by Django 5.2.5 on 2025-08-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_trailer_remove_car_driver_remove_car_trailer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('partner_type', models.CharField(choices=[('sender', 'Відправник'), ('receiver', 'Отримувач'), ('both', 'Відправник та отримувач')], default='sender', max_length=20, verbose_name='Тип партнера')),
            ],
        ),
        migrations.CreateModel(
            name='UnloadingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва місця')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
                ('place_type', models.CharField(choices=[('elevator', 'Елеватор'), ('warehouse', 'Склад'), ('factory', 'Завод'), ('other', 'Інше')], default='elevator', max_length=50, verbose_name='Тип місця')),
            ],
        ),
    ]
