# Generated by Django 5.2.5 on 2025-11-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_field_place_trailer_alter_culture_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['number'], 'verbose_name': 'Авто', 'verbose_name_plural': 'Автомобілі'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['full_name'], 'verbose_name': 'Водій', 'verbose_name_plural': 'Водії'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['name'], 'verbose_name': 'Поле', 'verbose_name_plural': 'Поля'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name'], 'verbose_name': 'Місце', 'verbose_name_plural': 'Місця'},
        ),
        migrations.AlterModelOptions(
            name='trailer',
            options={'ordering': ['number'], 'verbose_name': 'Причеп', 'verbose_name_plural': 'Причепи'},
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер авто'),
        ),
    ]
