# Generated by Django 5.2.5 on 2025-08-30 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_partner_unloadingplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='default_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='directory.driver', verbose_name='Закріплений водій'),
        ),
    ]
