# Generated by Django 5.2.5 on 2025-09-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_car_default_driver'),
        ('logistics', '0006_alter_arrivaljournal_weight_gross_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unloadingplace',
            name='cultures',
            field=models.ManyToManyField(through='logistics.StockBalance', to='directory.culture'),
        ),
    ]
